- name: Create user ansible
  win_user: 
    name: ansible
    password: Password123
    state: present
    groups:
       - Users Administrators
  become: yes  
  ignore_errors: yes
  register: result